name: gpt_detector
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.9+15

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.3

  # Networking
  dio: ^5.1.2
  pretty_dio_logger: ^1.3.1
  internet_connection_checker: ^1.0.0+1

  # Caching
  shared_preferences: ^2.1.0

  # Dependency injection
  injectable: ^2.1.1
  get_it: ^7.6.0

  # Data class generation
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  # Functional programming
  dartz: ^0.10.1

  # Utility
  google_mlkit_language_id: ^0.7.0
  permission_handler: ^10.2.0
  device_info_plus: ^8.1.0
  image_picker: ^0.8.6+1
  image_cropper: ^3.0.1
  flutter_dotenv: ^5.0.2
  in_app_review: ^2.0.6
  url_launcher: ^6.1.8
  share_plus: ^6.3.1
  intl: ^0.18.0

  # OCR
  google_mlkit_text_recognition: ^0.8.1

  # Packages
  form_inputs:
    path: packages/form_inputs

  # UI
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.1.1+1

  # App Icons
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  bloc_test: ^9.1.3

  # Code gen
  freezed: ^2.3.4
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  injectable_generator: ^2.1.5

  # Linter
  very_good_analysis: ^5.0.0+1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#6200EE"
  # Padding 8%
  adaptive_icon_foreground: "assets/icons/logo_foreground.png"

flutter_native_splash:
  android: true
  ios: true
  android12: true
  color: "#6200EE"
  image: "assets/icons/logo_no_bg.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - env/
    - assets/icons/
